#!/bin/env python3
import sys
CPLength, PtrLenth, OAMObjects, Str = 0x5A0, 40, 11*0xFFFF, ""
ProgramAddr = CPLength+PtrLenth+OAMObjects
def hex2(x,l=2,j=False):x=hex(x)[2:][-l:];return("0x"*j)+("0"*(l-len(x)))+x.upper()
if len(sys.argv)>1:
 infile, name = open(sys.argv[1],"rb").read()[ProgramAddr+1:], sys.argv[2].split('\\'if sys.platform=="nt"else"/")[-1].split(".")[0]
 for i in infile: Str+="0x"+hex2(i)+"@"
 print("#ruledef extract_data {\n extract_data => "+Str[:-1]+"\n}\n"+str(len(Str)-1))

#!/bin/env python3
import sys
CPLength, PtrLenth, OAMObjects, Str, l = 0x5A0, 40, 11*0xFFFF, [""], 0
ProgramAddr = CPLength+PtrLenth+OAMObjects
def hex2(x,l=2,j=False):x=hex(x)[2:][-l:];return("0x"*j)+("0"*(l-len(x)))+x.upper()
if len(sys.argv)>2:
 with open(sys.argv[2],"w") as outfile:
  infile, name = open(sys.argv[1],"rb").read()[ProgramAddr+1:], sys.argv[2].split('\\'if sys.platform=="nt"else"/")[-1].split(".")[0]
  
  for j,i in enumerate(infile):
   Str[-1]+="0x"+hex2(i)+"@"
   if j%513==512:
    Str[-1] = Str[-1][:-1]
    Str.append("")
  Str[-1] = Str[-1][:-1]
  outfile.write(''';########################################\n;## Auto-generated by exact-ruledef.py ##\n;########################################\n#ruledef extract_data {\n'''+'\n'.join([f" {name}_data{i} => {Str[i]}" for i in range(len(Str))])+'''\n}\n'''+name+'''_len = '''+str(len(infile)*2))

